countries_used <- c(
  "ABW", "ADO", "AFG", "AGO", "ALB", "AND", "ARB", "ARE", "ARG", "ARM", "ASM",
  "ATG", "AUS", "AUT", "AZE", "BDI", "BEL", "BEN", "BFA", "BGD", "BGR", "BHR",
  "BHS", "BIH", "BLR", "BLZ", "BMU", "BOL", "BRA", "BRB", "BRN", "BTN", "BWA",
  "CAF", "CAN", "CEB", "CHE", "CHI", "CHL", "CHN", "CIV", "CMR", "COD", "COG",
  "COL", "COM", "CPV", "CRI", "CSS", "CUB", "CUW", "CYM", "CYP", "CZE", "DEU",
  "DJI", "DMA", "DNK", "DOM", "DZA", "EAP", "EAR", "EAS", "ECA", "ECS", "ECU",
  "EGY", "EMU", "ERI", "ESP", "EST", "ETH", "EUU", "FCS", "FIN", "FJI", "FRA",
  "FRO", "FSM", "GAB", "GBR", "GEO", "GHA", "GIB", "GIN", "GMB", "GNB", "GNQ",
  "GRC", "GRD", "GRL", "GTM", "GUM", "GUY", "HIC", "HKG", "HND", "HPC", "HRV",
  "HTI", "HUN", "IBD", "IBT", "IDA", "IDB", "IDN", "IDX", "IMN", "IND", "INX",
  "IRL", "IRN", "IRQ", "ISL", "ISR", "ITA", "JAM", "JOR", "JPN", "KAZ", "KEN",
  "KGZ", "KHM", "KIR", "KNA", "KOR", "KWT", "LAC", "LAO", "LBN", "LBR", "LBY",
  "LCA", "LCN", "LDC", "LIC", "LIE", "LKA", "LMC", "LMY", "LSO", "LTE", "LTU",
  "LUX", "LVA", "MAC", "MAF", "MAR", "MCO", "MDA", "MDG", "MDV", "MEA", "MEX",
  "MHL", "MIC", "MKD", "MLI", "MLT", "MMR", "MNA", "MNE", "MNG", "MNP", "MOZ",
  "MRT", "MUS", "MWI", "MYS", "NAC", "NAM", "NCL", "NER", "NGA", "NIC", "NLD",
  "NOR", "NPL", "NRU", "NZL", "OED", "OMN", "OSS", "PAK", "PAN", "PER", "PHL",
  "PLW", "PNG", "POL", "PRE", "PRI", "PRK", "PRT", "PRY", "PSE", "PSS", "PST",
  "PYF", "QAT", "ROM", "ROU", "RUS", "RWA", "SAS", "SAU", "SDN", "SEN", "SGP",
  "SLB", "SLE", "SLV", "SMR", "SOM", "SRB", "SSA", "SSD", "SSF", "SST", "STP",
  "SUR", "SVK", "SVN", "SWE", "SWZ", "SXM", "SYC", "SYR", "TCA", "TCD", "TEA",
  "TEC", "TGO", "THA", "TJK", "TKM", "TLA", "TLS", "TMN", "TMP", "TON", "TSA",
  "TSS", "TTO", "TUN", "TUR", "TUV", "TWN", "TZA", "UGA", "UKR", "UMC", "URY",
  "USA", "UZB", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WBG", "WLD", "WSM",
  "XKX", "YEM", "ZAF", "ZAR", "ZMB", "ZWE")
